# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 10112efa687e13fffca2649df0a1ae403b81c3ca116ec69a9f1919a488e6fd151649cfb13f7ea63f4f1fd8ada8632fdd7c791928e8c2a00a839b91d495269a40

test:
  secret_key_base: 4489cf8ef7cb96a296ef670b521afb096b7ef7b27218e1eff3bdc6094a17084c2fe9ae8c1ee343a142d4b6cca03cd566148dc7eb7c02d10e073f79e82dd1e797

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
